POST http://localhost:3001/api/books
Content-Type: application/json

[
  {
    "_id": "Rough Around The Edges",
    "rank": "#00",
    "name": "Rough Around The Edges",
    "author": "Crystal Chard",
    "rating": "4.8 out of 5 stars",
    "price": "$6.99"
  },
  {
    "_id": "Goode Girls Steal: A Lesbian Romance Series (A…",
    "rank": "#00",
    "name": "Goode Girls Steal: A Lesbian Romance Series (A…",
    "author": "J.J. Arias",
    "rating": "4.6 out of 5 stars",
    "price": "$3.99"
  }
]