POST http://localhost:3001/books
Content-Type: application/json

{
    "rank": "#40",
    "name": "Demanding Boss",
    "author": "Clara Reese",
    "rating": "4.1 out of 5 stars",
    "price": "$3.99"
}
